[build]
{% if target == "riscv32ec-unknown-none-elf" -%}
target = "riscv32ec-unknown-none-elf.json"
{%- elsif target == "riscv32imfc-unknown-none-elf" -%}
target = "riscv32imfc-unknown-none-elf.json"
{%- else -%}
target = "{{ target }}"
{%- endif %}

[target."{{ target }}"]
#-------------------------------------------------------
# Modified by KotukoHumibana
# Orignal Work by ch32-hal

{% if os == "windows" -%}
runner = "./flash/flash.bat"
{%- elsif os == "linux" or os == "macos" -%}
runner = "sh ./flash/flash.sh"
{%- endif %}
#--------------------------------------------------------

{% if target == "riscv32ec-unknown-none-elf" or target == "riscv32imfc-unknown-none-elf" -%}
[unstable]
build-std = ["core"]
json-target-spec = true
{% endif -%}
